M48
; DRILL file {KiCad (6.0.0)} date Sun May  1 21:30:34 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-01T21:30:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0120
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0150
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0190
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0240
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T6C0.0380
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T7C0.0480
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T8C0.0600
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T9C0.0760
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T10C0.0866
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T11C0.0890
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T12C0.0960
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T13C0.1063
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T14C0.1160
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T15C0.1260
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T16C0.1440
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T17C0.1693
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T18C0.1700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T19C0.1960
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T20C0.2087
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T21C0.2520
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T22C0.2570
%
G90
G05
T1
X3.75Y-4.01
T2
X3.75Y-3.96
T3
X3.75Y-3.91
T4
X3.75Y-3.86
T5
X3.75Y-3.81
T6
X3.75Y-3.75
T7
X3.75Y-3.68
T8
X3.75Y-3.6
T9
X3.75Y-3.51
T10
X7.75Y-3.5
T11
X8.85Y-3.75
T12
X3.75Y-3.4
T13
X7.8878Y-3.5
T14
X3.75Y-3.27
X8.7Y-3.75
T15
X8.0453Y-3.5
T16
X8.525Y-3.75
T17
X8.2421Y-3.5
T18
X8.325Y-3.75
T19
X8.1Y-3.75
T20
X8.4783Y-3.5
T21
X8.7539Y-3.5
T22
X7.825Y-3.75
T0
M30
